version: '3'

services:
  quoteui:
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
    image: registry.docker.upcbq.com:443/quoteui:${TAG:-latest}
    container_name: quoteui
    restart: unless-stopped
    ports:
      - ${PORT:-8080}:80
    environment:
      - PORT
