version: '3'

services:
  quoteui:
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
      args:
        PORT: ${PORT}
    image: quoteui
    container_name: quoteui
    restart: unless-stopped
    ports:
      - ${PORT}:80
    environment:
      - PORT
